### ISSUE TITLE
Improve download speed

### ISSUE THREAD

**Issue by wvangeit** [BlueBrain/SSCxEModelExamples#22]
At the moment it takes a fairly long time to download this repo. The content of the repo is not that large, is something in the history slowing us down @anilbey ?

**Comment by anilbey** [comment]
Do you have the logs? It can be the decompressing process of git. After you decompress the repo becomes much bigger.

I don't think there was a large file in the history that got deleted afterwards. It's the opposite, the datasets are added later.

**Comment by anilbey** [comment]
`git clone` with depth=1 took 1m 47s on a fast internet connection.

```
❯ git clone git@github.com:BlueBrain/SSCxEModelExamples.git --depth=1
Cloning into 'SSCxEModelExamples'...
remote: Enumerating objects: 12517, done.
remote: Counting objects: 100% (12517/12517), done.
remote: Compressing objects: 100% (12359/12359), done.
remote: Total 12517 (delta 152), reused 12451 (delta 143), pack-reused 0
Receiving objects: 100% (12517/12517), 394.43 MiB | 4.28 MiB/s, done.
Resolving deltas: 100% (152/152), done.
Updating files: 100% (12567/12567), done.
```

**Comment by wvangeit** [comment]
Ok, sorry, I didn't measure the size of the cloned repo correctly
