### ISSUE TITLE
no Extractor class in BluePyEFE

### ISSUE THREAD

**Issue by a1eko** [BlueBrain/SSCxEModelExamples#25]
Example notebook on feature extraction stops at cell 7 with AttributeError: module 'bluepyefe' has no attribute 'Extractor'.

**Comment by anilbey** [comment]
Thanks @a1eko for reporting it. Could you also provide the version of bluepyefe you are using please?

**Comment by a1eko** [comment]
Default one for pip3-install:
bluepyefe            2.2.46
efel                 4.1.86

**Comment by anilbey** [comment]
I see so the version should be `bluepyefe>=0.4,<2.0` as in `requirements.txt`.

https://github.com/BlueBrain/SSCxEModelExamples/blob/main/requirements.txt#L1

The requirements can directly be installed using `pip install -r requirements.txt`.
Note that somatic-validation has different requirements specified in `somatic-val-requirements.txt`
https://github.com/BlueBrain/SSCxEModelExamples/blob/main/somatic_validation/somatic-val-requirements.txt.
